version: "2"
services:
    designer:
        image: fogflow/designer
        volumes:
            - ./config.json:/app/config.json                
        ports:
            - 8080:8080
            - 1030:1030
        depends_on: 
            - discovery
            - broker
    discovery:
        image: fogflow/discovery
        volumes:
            - ./config.json:/config.json                        
        ports:
            - 8090:8090
        depends_on: 
            - postgis
    broker:
        image: fogflow/broker
        volumes:
            - ./config.json:/config.json                        
        ports:
            - 8070:8070
        depends_on: 
            - discovery
    master:
        image: fogflow/master
        volumes:
            - ./config.json:/config.json                        
        links:
            - rabbitmq        
        ports:
            - 1060:1060 
        depends_on: 
            - rabbitmq
            - discovery
            - broker     
    cloud_worker:
        image: fogflow/worker
        volumes:
            - /tmp:/tmp        
            - ./config.json:/config.json                
            - /var/run/docker.sock:/var/run/docker.sock                    
    postgis:
        image: mdillon/postgis
        ports:
            - 5432:5432        
    rabbitmq:
        image: tutum/rabbitmq
        ports:
            - 5672:5672
        environment:
            - RABBITMQ_PASS=mypass   
